version: 2
jobs:
   python-3.5:
    docker:
      - image: circleci/python:3.5

    steps:
      - run:
          name: dependencies
          command: |
          pip install --user \
          -r requirements.txt

workflows:
  version: 2
  test:
    override:
      - nosetests tests/math-test.py
    jobs:
      - python-3.5
