version: 2
jobs:
  python-3.5:
    docker:
      - image: circleci/python:3.5
  
  build:  
    test:
      override:
        - nosetests tests/math-test.py
    
  steps:
    - run:
        name: dependencies
        command: |
          pip install \
          -r requirements.txt
  
  

